In [ ]:
from sklearn.datasets import make_classification, make_regression

X, y = make_classification(
    n_samples=1112664,
    n_features=
)

In [38]:
import pandas as pd

df = pd.read_csv("cleaned_real_estate.csv")
df.head()

      Price  Area_SqFt  Bedrooms  Location  Bathrooms  Source  Price_Per_SqFt
0  0.117684   0.227638  0.333333  0.003587   0.333333     0.0        0.256978
1  0.089664   0.401663  0.666667  0.003587   0.333333     0.0        0.117963
2  0.075094   0.178326  0.000000  0.436827   0.000000     0.0        0.201682
3  0.162516   0.479931  0.666667  0.712919   0.333333     0.0        0.181380
4  0.200624   0.686353  0.666667  0.790241   0.666667     0.0        0.159936

In [39]:
df.shape

(1112664, 7)

In [40]:
import numpy as np
import pandas as pd

n_samples = len(df)

In [41]:
#1. Age_of_Property:
age = np.random.gamma(shape=2.0, scale=10.0, size=n_samples).astype(int)
age = np.clip(age,0,100)

In [42]:
#2. Parking:
parking = np.random.choice([0,1,2,3,4], size=n_samples, p=[0.1,0.3,0.3,0.1,0.2])

In [43]:
#3. Nearby_Schools:
schools = np.random.poisson(lam=3, size=n_samples)
schools = np.clip(schools, 0, 10)

In [44]:
#4. Dist_to_city: 
dist = np.random.uniform(1.2,45,size=n_samples).round(2)

In [45]:
#Adding the new features to the Dataframe:
df['Age_of_Property'] = age
df['Parking'] = parking
df['Nearby_Schools'] = schools
df['Dist_to_city'] = dist

print(df[['Age_of_Property','Parking','Nearby_Schools','Dist_to_city']].head(7) )

   Age_of_Property  Parking  Nearby_Schools  Dist_to_city
0                9        4               4         39.96
1               18        1               1         10.99
2               15        0               2         41.68
3                8        4               2         44.34
4                4        4               4         12.00
5               16        0               2          1.52
6               25        2               2         18.73

In [46]:
df_synthetic = df

In [47]:
df_synthetic.head()

,Price,Area_SqFt,Bedrooms,Location,Bathrooms,Source,Price_Per_SqFt,Age_of_Property,Parking,Nearby_Schools,Dist_to_city
0,0.117684,0.227638,0.333333,0.003587,0.333333,0.0,0.256978,9,4,4,39.96
1,0.089664,0.401663,0.666667,0.003587,0.333333,0.0,0.117963,18,1,1,10.99
2,0.075094,0.178326,0.000000,0.436827,0.000000,0.0,0.201682,15,0,2,41.68
3,0.162516,0.479931,0.666667,0.712919,0.333333,0.0,0.181380,8,4,2,44.34
4,0.200624,0.686353,0.666667,0.790241,0.666667,0.0,0.159936,4,4,4,12.00

In [48]:
df_synthetic.shape

(1112664, 11)

In [49]:
#Converting to save memory:
df_synthetic['Age_of_Property'] = df_synthetic['Age_of_Property'].astype('int8')
df_synthetic['Parking'] = df_synthetic['Parking'].astype('int8')
df_synthetic['Nearby_Schools']  = df_synthetic['Nearby_Schools'].astype('int8')
df_synthetic['Dist_to_city'] = df_synthetic['Dist_to_city'].astype('float32')

In [50]:
#Storing the dataset:
df_synthetic.to_csv('new_synthetic_dataset.csv', index=False)

In [53]:
#Loading dataset containing new features having synthetic values assigned:
df_synthetic_new = pd.read_csv("new_synthetic_dataset.csv")
df_synthetic_new.head(100)

,Price,Area_SqFt,Bedrooms,Location,Bathrooms,Source,Price_Per_SqFt,Age_of_Property,Parking,Nearby_Schools,Dist_to_city
0,0.117684,0.227638,0.333333,0.003587,0.333333,0.0,0.256978,9,4,4,39.96
1,0.089664,0.401663,0.666667,0.003587,0.333333,0.0,0.117963,18,1,1,10.99
2,0.075094,0.178326,0.000000,0.436827,0.000000,0.0,0.201682,15,0,2,41.68
3,0.162516,0.479931,0.666667,0.712919,0.333333,0.0,0.181380,8,4,2,44.34
4,0.200624,0.686353,0.666667,0.790241,0.666667,0.0,0.159936,4,4,4,12.00
...,...,...,...,...,...,...,...,...,...,...,...
95,0.089664,0.178899,0.333333,0.026134,0.000000,0.0,0.240172,54,1,4,23.72
96,0.151308,0.393922,1.000000,0.026134,0.333333,0.0,0.202645,11,3,2,38.74
97,0.240972,0.589736,0.333333,0.026134,0.666667,0.0,0.221758,21,2,1,4.73
98,0.154671,0.250573,0.333333,0.026134,0.333333,0.0,0.310723,79,1,6,12.88
99,0.323912,0.775803,1.000000,0.026134,1.000000,0.0,0.229773,26,4,3,9.70